import collections
d= collections.deque()
d.append(5)
d.append(6)
d.append(10)
d.append(10)
d.append(2)
d.append(3)
d.append(7)
print('Deque D: ',d)
print('Length: ',len(d))
d.rotate(5)
print('Deque D: ',d)
d.popleft()
d.pop()
print('Deque D: ',d)
print('Length: ',len(d))